# Generated by Django 2.1.7 on 2019-03-05 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phoneNumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09999999999' or '+989999999999'.", regex='^(\\+98|0)?9\\d{9}$')]),
        ),
    ]
